export interface Word {
  id: string;
  hebrew: string;
  hebrewWithVowels?: string;
  french: string;
  isCustom?: boolean;
}

export interface VocabularyList {
  id: string;
  name: string;
  description: string;
  words: Word[];
}

export const vocabularyLists: VocabularyList[] = [
  {
    id: 'maison',
    name: 'Maison & Habitat',
    description: 'Vocabulaire de la maison et aménagement intérieur',
    words: [
      { id: '1', hebrew: 'דלת', hebrewWithVowels: 'דַלֶת', french: 'Porte' },
      { id: '2', hebrew: 'חלון', hebrewWithVowels: 'חַלוֹן', french: 'Fenêtre' },
      { id: '3', hebrew: 'מדרגות', hebrewWithVowels: 'מַדְרֵגוֹת', french: 'Escaliers' },
      { id: '4', hebrew: 'קיר', hebrewWithVowels: 'קִיר', french: 'Mur' },
      { id: '5', hebrew: 'תקרה', hebrewWithVowels: 'תִקְרָה', french: 'Plafond' },
      { id: '6', hebrew: 'רצפה', hebrewWithVowels: 'רִצְפָה', french: 'Sol/Plancher' },
      { id: '7', hebrew: 'ריהוט', hebrewWithVowels: 'רִיהוּט', french: 'Mobilier' },
      { id: '8', hebrew: 'מטבח', hebrewWithVowels: 'מִטְבַּח', french: 'Cuisine' },
      { id: '9', hebrew: 'חדר שינה', hebrewWithVowels: 'חֶדֶר שֵׁינָה', french: 'Chambre à coucher' },
      { id: '10', hebrew: 'אמבטיה', hebrewWithVowels: 'אַמְבַּטְיָה', french: 'Salle de bain' },
      { id: '11', hebrew: 'סלון', hebrewWithVowels: 'סָלוֹן', french: 'Salon' },
      { id: '12', hebrew: 'משכנתא', hebrewWithVowels: 'מִשְׁכַּנְתָּא', french: 'Hypothèque' },
      { id: '13', hebrew: 'דירה', hebrewWithVowels: 'דִּירָה', french: 'Appartement' },
      { id: '14', hebrew: 'בית', hebrewWithVowels: 'בַּיִת', french: 'Maison' },
      { id: '15', hebrew: 'חדר', hebrewWithVowels: 'חֶדֶר', french: 'Chambre' },
      { id: '16', hebrew: 'מקרר', hebrewWithVowels: 'מִקְרֵר', french: 'Réfrigérateur' },
      { id: '17', hebrew: 'כיריים', hebrewWithVowels: 'כִּיְרַיִם', french: 'Cuisinière' },
      { id: '18', hebrew: 'כיור', hebrewWithVowels: 'כִּיּוֹר', french: 'Évier' },
      { id: '19', hebrew: 'ספה', hebrewWithVowels: 'סָפָה', french: 'Canapé' },
      { id: '20', hebrew: 'שולחן', hebrewWithVowels: 'שֻׁלְחָן', french: 'Table' },
      { id: '21', hebrew: 'כסא', hebrewWithVowels: 'כִּסֵּא', french: 'Chaise' },
      { id: '22', hebrew: 'מיטה', hebrewWithVowels: 'מִיטָּה', french: 'Lit' },
      { id: '23', hebrew: 'ארון', hebrewWithVowels: 'אָרוֹן', french: 'Armoire' },
      { id: '24', hebrew: 'מראה', hebrewWithVowels: 'מִרְאָה', french: 'Miroir' },
      { id: '25', hebrew: 'נר', hebrewWithVowels: 'נֵר', french: 'Chandelle' },
    ],
  },
  {
    id: 'emotions',
    name: 'Émotions & Sentiments',
    description: 'Verbes et vocabulaire des émotions',
    words: [
      { id: '1', hebrew: 'להרגיש', hebrewWithVowels: 'לְהַרְגִּישׁ', french: 'Sentir/Ressentir' },
      { id: '2', hebrew: 'לשמוח', hebrewWithVowels: 'לִשְׂמוֹחַ', french: 'Se réjouir' },
      { id: '3', hebrew: 'להצטער', hebrewWithVowels: 'לְהִצְטָעֵר', french: 'Regretter' },
      { id: '4', hebrew: 'להתרגז', hebrewWithVowels: 'לְהִתְרַגַּז', french: 'S\'énerver/Se fâcher' },
      { id: '5', hebrew: 'לפחד', hebrewWithVowels: 'לִפְחוֹד', french: 'Avoir peur' },
      { id: '6', hebrew: 'להתקצף', hebrewWithVowels: 'לְהִתְקַצֵּף', french: 'Être furieux' },
      { id: '7', hebrew: 'להתעצבן', hebrewWithVowels: 'לְהִתְעַצְּבֵן', french: 'Être déprimé' },
      { id: '8', hebrew: 'להרגע', hebrewWithVowels: 'לְהַרְגִּיעַ', french: 'Se calmer' },
      { id: '9', hebrew: 'להיות עצוב', hebrewWithVowels: 'לִהְיוֹת עָצוּב', french: 'Être triste' },
      { id: '10', hebrew: 'לחוש אימה', hebrewWithVowels: 'לַחוּשׁ אֵימָה', french: 'Ressentir de la terreur' },
      { id: '11', hebrew: 'אהבה', hebrewWithVowels: 'אַהֲבָה', french: 'Amour' },
      { id: '12', hebrew: 'שנאה', hebrewWithVowels: 'שִׂנְאָה', french: 'Haine' },
      { id: '13', hebrew: 'תקווה', hebrewWithVowels: 'תִּקְוָה', french: 'Espoir' },
      { id: '14', hebrew: 'ייאוש', hebrewWithVowels: 'יְאוּשׁ', french: 'Désespoir' },
      { id: '15', hebrew: 'כמיהה', hebrewWithVowels: 'כְּמִיהָה', french: 'Nostalgie/Yearning' },
      { id: '16', hebrew: 'שמחה', hebrewWithVowels: 'שִׂמְחָה', french: 'Joie' },
      { id: '17', hebrew: 'עצב', hebrewWithVowels: 'עֶצֶב', french: 'Tristesse' },
      { id: '18', hebrew: 'כעס', hebrewWithVowels: 'כַּעַס', french: 'Colère' },
      { id: '19', hebrew: 'בושה', hebrewWithVowels: 'בּוּשָׁה', french: 'Honte' },
      { id: '20', hebrew: 'גאווה', hebrewWithVowels: 'גַּאֲוָה', french: 'Fierté' },
      { id: '21', hebrew: 'קנאה', hebrewWithVowels: 'קִנְאָה', french: 'Jalousie' },
      { id: '22', hebrew: 'חסד', hebrewWithVowels: 'חֶסֶד', french: 'Compassion' },
      { id: '23', hebrew: 'צער', hebrewWithVowels: 'צַעַר', french: 'Chagrin' },
      { id: '24', hebrew: 'הנאה', hebrewWithVowels: 'הַנָּאָה', french: 'Plaisir' },
      { id: '25', hebrew: 'דאגה', hebrewWithVowels: 'דַּאֲגָה', french: 'Inquiétude' },
    ],
  },
  {
    id: 'family',
    name: 'Famille & Relations',
    description: 'Vocabulaire familial avancé',
    words: [
      { id: '1', hebrew: 'סב/סבה', hebrewWithVowels: 'סַב/סָבָה', french: 'Grand-père/mère' },
      { id: '2', hebrew: 'דוד/דודה', hebrewWithVowels: 'דּוֹד/דּוֹדָה', french: 'Oncle/Tante' },
      { id: '3', hebrew: 'בן דוד/בת דודה', hebrewWithVowels: 'בֵּן דוֹד/בַּת דוֹדָה', french: 'Cousin/Cousine' },
      { id: '4', hebrew: 'חמורה', hebrewWithVowels: 'חַמּוּרָה', french: 'Belle-mère (époux)' },
      { id: '5', hebrew: 'חתן', hebrewWithVowels: 'חָתָן', french: 'Gendre' },
      { id: '6', hebrew: 'כלה', hebrewWithVowels: 'כַּלָּה', french: 'Mariée' },
      { id: '7', hebrew: 'אחיינייה', hebrewWithVowels: 'אַחְיָנִית', french: 'Nièce' },
      { id: '8', hebrew: 'אחיין', hebrewWithVowels: 'אַחְיָן', french: 'Neveu' },
      { id: '9', hebrew: 'משפחה גדולה', hebrewWithVowels: 'מִשְׁפָּחָה גְדוֹלָה', french: 'Grande famille' },
      { id: '10', hebrew: 'יחסים משפחתיים', hebrewWithVowels: 'יְחָסִים מִשְׁפַּחְתִּיִּים', french: 'Relations familiales' },
      { id: '11', hebrew: 'אב', hebrewWithVowels: 'אָב', french: 'Père' },
      { id: '12', hebrew: 'אם', hebrewWithVowels: 'אֵם', french: 'Mère' },
      { id: '13', hebrew: 'בן', hebrewWithVowels: 'בֵּן', french: 'Fils' },
      { id: '14', hebrew: 'בת', hebrewWithVowels: 'בַּת', french: 'Fille' },
      { id: '15', hebrew: 'אח', hebrewWithVowels: 'אָח', french: 'Frère' },
      { id: '16', hebrew: 'אחות', hebrewWithVowels: 'אָחוֹת', french: 'Sœur' },
      { id: '17', hebrew: 'בעל', hebrewWithVowels: 'בַּעַל', french: 'Mari/Époux' },
      { id: '18', hebrew: 'אישה', hebrewWithVowels: 'אִשָּׁה', french: 'Femme/Épouse' },
      { id: '19', hebrew: 'ילד/ילדה', hebrewWithVowels: 'יֶלֶד/יַלְדָּה', french: 'Enfant' },
      { id: '20', hebrew: 'חמי/חמות', hebrewWithVowels: 'חָמִי/חָמוֹת', french: 'Beau-père/mère' },
      { id: '21', hebrew: 'גיס', hebrewWithVowels: 'גִּיס', french: 'Beau-frère' },
      { id: '22', hebrew: 'גיסה', hebrewWithVowels: 'גִּיסָה', french: 'Belle-sœur' },
      { id: '23', hebrew: 'סמיך קרוב', hebrewWithVowels: 'סָמִיךְ קָרוֹב', french: 'Proche' },
      { id: '24', hebrew: 'מעמד משפחתי', hebrewWithVowels: 'מַעֲמַד מִשְׁפַּחְתִּי', french: 'Statut familial' },
      { id: '25', hebrew: 'תינוק', hebrewWithVowels: 'תִּינוֹק', french: 'Bébé' },
    ],
  },
  {
    id: 'verbs',
    name: 'Verbes Courants',
    description: 'Verbes pratiques et fréquents',
    words: [
      { id: '1', hebrew: 'ללכת', hebrewWithVowels: 'לָלֶכֶת', french: 'Aller' },
      { id: '2', hebrew: 'לבוא', hebrewWithVowels: 'לָבוֹא', french: 'Venir' },
      { id: '3', hebrew: 'לשמוע', hebrewWithVowels: 'לִשְׁמוֹעַ', french: 'Entendre' },
      { id: '4', hebrew: 'לראות', hebrewWithVowels: 'לִרְאוֹת', french: 'Voir' },
      { id: '5', hebrew: 'לדבר', hebrewWithVowels: 'לְדַבֵּר', french: 'Parler' },
      { id: '6', hebrew: 'לשתוק', hebrewWithVowels: 'לִשְׁתוֹק', french: 'Se taire' },
      { id: '7', hebrew: 'לאכול', hebrewWithVowels: 'לֶאֱכוֹל', french: 'Manger' },
      { id: '8', hebrew: 'לשתות', hebrewWithVowels: 'לִשְׁתוֹת', french: 'Boire' },
      { id: '9', hebrew: 'לישון', hebrewWithVowels: 'לִישׁוֹן', french: 'Dormir' },
      { id: '10', hebrew: 'להיקום', hebrewWithVowels: 'לְהִיקוּם', french: 'Se lever' },
      { id: '11', hebrew: 'לכתוב', hebrewWithVowels: 'לִכְתּוֹב', french: 'Écrire' },
      { id: '12', hebrew: 'לקרוא', hebrewWithVowels: 'לִקְרוֹא', french: 'Lire' },
      { id: '13', hebrew: 'להבין', hebrewWithVowels: 'לְהָבִין', french: 'Comprendre' },
      { id: '14', hebrew: 'ללמוד', hebrewWithVowels: 'לִלְמוֹד', french: 'Étudier' },
      { id: '15', hebrew: 'לעבוד', hebrewWithVowels: 'לַעֲבוֹד', french: 'Travailler' },
      { id: '16', hebrew: 'לשחק', hebrewWithVowels: 'לִשְׂחוֹק', french: 'Jouer' },
      { id: '17', hebrew: 'לחיות', hebrewWithVowels: 'לַחֲיוֹת', french: 'Vivre' },
      { id: '18', hebrew: 'למות', hebrewWithVowels: 'לָמוּת', french: 'Mourir' },
      { id: '19', hebrew: 'לתת', hebrewWithVowels: 'לָתֵת', french: 'Donner' },
      { id: '20', hebrew: 'לקחת', hebrewWithVowels: 'לָקַחַת', french: 'Prendre' },
      { id: '21', hebrew: 'לעזור', hebrewWithVowels: 'לַעֲזוֹר', french: 'Aider' },
      { id: '22', hebrew: 'לחפש', hebrewWithVowels: 'לַחְפֵּשׂ', french: 'Chercher' },
      { id: '23', hebrew: 'למצוא', hebrewWithVowels: 'לִמְצוֹא', french: 'Trouver' },
      { id: '24', hebrew: 'לחכות', hebrewWithVowels: 'לַחְכּוֹת', french: 'Attendre' },
      { id: '25', hebrew: 'להכין', hebrewWithVowels: 'לְהָכִין', french: 'Préparer' },
    ],
  },
  {
    id: 'food',
    name: 'Nourriture & Cuisine',
    description: 'Aliments et vocabulaire culinaire',
    words: [
      { id: '1', hebrew: 'לחם', hebrewWithVowels: 'לֶחֶם', french: 'Pain' },
      { id: '2', hebrew: 'עוף', hebrewWithVowels: 'עוֹף', french: 'Volaille/Poulet' },
      { id: '3', hebrew: 'בשר', hebrewWithVowels: 'בָּשָׂר', french: 'Viande' },
      { id: '4', hebrew: 'דגים', hebrewWithVowels: 'דָּגִים', french: 'Poisson' },
      { id: '5', hebrew: 'ירקות', hebrewWithVowels: 'יְרָקוֹת', french: 'Légumes' },
      { id: '6', hebrew: 'פירות', hebrewWithVowels: 'פֵּרוֹת', french: 'Fruits' },
      { id: '7', hebrew: 'ביצה', hebrewWithVowels: 'בֵּיצָה', french: 'Œuf' },
      { id: '8', hebrew: 'חומוס', hebrewWithVowels: 'חֻמּוּס', french: 'Houmous' },
      { id: '9', hebrew: 'מלח', hebrewWithVowels: 'מֶלַח', french: 'Sel' },
      { id: '10', hebrew: 'סוכר', hebrewWithVowels: 'סֻכָּר', french: 'Sucre' },
      { id: '11', hebrew: 'גבינה', hebrewWithVowels: 'גְּבִינָה', french: 'Fromage' },
      { id: '12', hebrew: 'חלב', hebrewWithVowels: 'חָלָב', french: 'Lait' },
      { id: '13', hebrew: 'דבש', hebrewWithVowels: 'דְּבַשׁ', french: 'Miel' },
      { id: '14', hebrew: 'בטטה', hebrewWithVowels: 'בָּטָטָה', french: 'Pomme de terre' },
      { id: '15', hebrew: 'עגבנייה', hebrewWithVowels: 'עַגְבָּנִיָּה', french: 'Tomate' },
      { id: '16', hebrew: 'מלפפון', hebrewWithVowels: 'מְלַפְּפוֹן', french: 'Concombre' },
      { id: '17', hebrew: 'בצל', hebrewWithVowels: 'בָּצָל', french: 'Oignon' },
      { id: '18', hebrew: 'שום', hebrewWithVowels: 'שׁוּם', french: 'Ail' },
      { id: '19', hebrew: 'בננה', hebrewWithVowels: 'בָּנָנָה', french: 'Banane' },
      { id: '20', hebrew: 'תפוח', hebrewWithVowels: 'תַּפּוּחַ', french: 'Pomme' },
      { id: '21', hebrew: 'לימון', hebrewWithVowels: 'לִימוֹן', french: 'Citron' },
      { id: '22', hebrew: 'פסטה', hebrewWithVowels: 'פַּסְטָה', french: 'Pâtes' },
      { id: '23', hebrew: 'אורז', hebrewWithVowels: 'אוּרֹז', french: 'Riz' },
      { id: '24', hebrew: 'טעם', hebrewWithVowels: 'טַעַם', french: 'Goût' },
      { id: '25', hebrew: 'מסעדה', hebrewWithVowels: 'מִסְעָדָה', french: 'Restaurant' },
    ],
  },
  {
    id: 'body',
    name: 'Corps & Santé',
    description: 'Parties du corps et vocabulaire médical',
    words: [
      { id: '1', hebrew: 'ראש', hebrewWithVowels: 'רֹאשׁ', french: 'Tête' },
      { id: '2', hebrew: 'עיניים', hebrewWithVowels: 'עֵינַיִם', french: 'Yeux' },
      { id: '3', hebrew: 'אוזן', hebrewWithVowels: 'אֹזֶן', french: 'Oreille' },
      { id: '4', hebrew: 'אף', hebrewWithVowels: 'אַף', french: 'Nez' },
      { id: '5', hebrew: 'פה', hebrewWithVowels: 'פֶּה', french: 'Bouche' },
      { id: '6', hebrew: 'שיניים', hebrewWithVowels: 'שִׁנַּיִם', french: 'Dents' },
      { id: '7', hebrew: 'לב', hebrewWithVowels: 'לֵב', french: 'Cœur' },
      { id: '8', hebrew: 'ריאות', hebrewWithVowels: 'רִיאוֹת', french: 'Poumons' },
      { id: '9', hebrew: 'כאב', hebrewWithVowels: 'כְּאֵב', french: 'Douleur' },
      { id: '10', hebrew: 'חום', hebrewWithVowels: 'חֹם', french: 'Fièvre' },
      { id: '11', hebrew: 'זרוע', hebrewWithVowels: 'זְרוֹעַ', french: 'Bras' },
      { id: '12', hebrew: 'רגל', hebrewWithVowels: 'רֶגֶל', french: 'Jambe' },
      { id: '13', hebrew: 'יד', hebrewWithVowels: 'יָד', french: 'Main' },
      { id: '14', hebrew: 'כף יד', hebrewWithVowels: 'כַּף יָד', french: 'Paume' },
      { id: '15', hebrew: 'אצבע', hebrewWithVowels: 'אֶצְבַּע', french: 'Doigt' },
      { id: '16', hebrew: 'כתף', hebrewWithVowels: 'כָּתֵף', french: 'Épaule' },
      { id: '17', hebrew: 'גב', hebrewWithVowels: 'גַּב', french: 'Dos' },
      { id: '18', hebrew: 'בטן', hebrewWithVowels: 'בֶּטֶן', french: 'Ventre' },
      { id: '19', hebrew: 'קרסול', hebrewWithVowels: 'קַרְסוּל', french: 'Cheville' },
      { id: '20', hebrew: 'עצם', hebrewWithVowels: 'עֶצֶם', french: 'Os' },
      { id: '21', hebrew: 'שריר', hebrewWithVowels: 'שִׁרִיר', french: 'Muscle' },
      { id: '22', hebrew: 'עור', hebrewWithVowels: 'עוֹר', french: 'Peau' },
      { id: '23', hebrew: 'דם', hebrewWithVowels: 'דָּם', french: 'Sang' },
      { id: '24', hebrew: 'חולי', hebrewWithVowels: 'חוֹלִי', french: 'Maladie' },
      { id: '25', hebrew: 'רופא', hebrewWithVowels: 'רוֹפֵא', french: 'Médecin' },
    ],
  },
  {
    id: 'work',
    name: 'Travail & Profession',
    description: 'Vocabulaire professionnel',
    words: [
      { id: '1', hebrew: 'עבודה', hebrewWithVowels: 'עֲבוֹדָה', french: 'Travail' },
      { id: '2', hebrew: 'משרד', hebrewWithVowels: 'מִשְׂרָד', french: 'Bureau' },
      { id: '3', hebrew: 'מחשב', hebrewWithVowels: 'מַחְשֵׁב', french: 'Ordinateur' },
      { id: '4', hebrew: 'טלפון', hebrewWithVowels: 'טֶלֶפוֹן', french: 'Téléphone' },
      { id: '5', hebrew: 'דוח', hebrewWithVowels: 'דּוּחַ', french: 'Rapport' },
      { id: '6', hebrew: 'פגישה', hebrewWithVowels: 'פְּגִישָׁה', french: 'Réunion' },
      { id: '7', hebrew: 'שכר', hebrewWithVowels: 'שָׂכָר', french: 'Salaire' },
      { id: '8', hebrew: 'חוזה', hebrewWithVowels: 'חוֹזֶה', french: 'Contrat' },
      { id: '9', hebrew: 'קריירה', hebrewWithVowels: 'קָרִיירָה', french: 'Carrière' },
      { id: '10', hebrew: 'מעסיק', hebrewWithVowels: 'מַעֲסִיק', french: 'Employeur' },
      { id: '11', hebrew: 'עובד', hebrewWithVowels: 'עוֹבֵד', french: 'Employé' },
      { id: '12', hebrew: 'מנהל', hebrewWithVowels: 'מְנַהֵל', french: 'Directeur/Manager' },
      { id: '13', hebrew: 'פרויקט', hebrewWithVowels: 'פְּרוֹיֶקְט', french: 'Projet' },
      { id: '14', hebrew: 'תיקייה', hebrewWithVowels: 'תִּקְיָּה', french: 'Dossier/Portefeuille' },
      { id: '15', hebrew: 'דדלין', hebrewWithVowels: 'דֶּדְלַיִן', french: 'Délai' },
      { id: '16', hebrew: 'ישיבה', hebrewWithVowels: 'יְשִׁיבָה', french: 'Séance/Réunion' },
      { id: '17', hebrew: 'עומק', hebrewWithVowels: 'עֹמֶק', french: 'Profondeur' },
      { id: '18', hebrew: 'הצלחה', hebrewWithVowels: 'הַצְלָחָה', french: 'Succès' },
      { id: '19', hebrew: 'כישרון', hebrewWithVowels: 'כִּשְׁרוֹן', french: 'Talent' },
      { id: '20', hebrew: 'ניסיון', hebrewWithVowels: 'נִסְיוֹן', french: 'Expérience' },
      { id: '21', hebrew: 'חינוך', hebrewWithVowels: 'חִנּוּךְ', french: 'Éducation/Formation' },
      { id: '22', hebrew: 'מקצוע', hebrewWithVowels: 'מִקְצוֹעַ', french: 'Profession' },
      { id: '23', hebrew: 'אחראיות', hebrewWithVowels: 'אַחְרַאִיּוּת', french: 'Responsabilité' },
      { id: '24', hebrew: 'שיתוף פעולה', hebrewWithVowels: 'שִׁיתּוּף פְּעֻלָּה', french: 'Collaboration' },
      { id: '25', hebrew: 'קידום', hebrewWithVowels: 'קִידּוּם', french: 'Promotion' },
    ],
  },
  {
    id: 'time',
    name: 'Temps & Calendrier',
    description: 'Jours, mois, saisons',
    words: [
      { id: '1', hebrew: 'יום ראשון', hebrewWithVowels: 'יוֹם רִאשׁוֹן', french: 'Dimanche' },
      { id: '2', hebrew: 'יום שני', hebrewWithVowels: 'יוֹם שֵׁנִי', french: 'Lundi' },
      { id: '3', hebrew: 'יום שלישי', hebrewWithVowels: 'יוֹם שְׁלִישִׁי', french: 'Mardi' },
      { id: '4', hebrew: 'יום רביעי', hebrewWithVowels: 'יוֹם רְבִיעִי', french: 'Mercredi' },
      { id: '5', hebrew: 'יום חמישי', hebrewWithVowels: 'יוֹם חֲמִישִׁי', french: 'Jeudi' },
      { id: '6', hebrew: 'יום שישי', hebrewWithVowels: 'יוֹם שִׁישִׁי', french: 'Vendredi' },
      { id: '7', hebrew: 'יום שבת', hebrewWithVowels: 'יוֹם שַׁבָּת', french: 'Samedi' },
      { id: '8', hebrew: 'חודש', hebrewWithVowels: 'חוֹדֶשׁ', french: 'Mois' },
      { id: '9', hebrew: 'עונה', hebrewWithVowels: 'עוֹנָה', french: 'Saison' },
      { id: '10', hebrew: 'שנה', hebrewWithVowels: 'שָׁנָה', french: 'Année' },
      { id: '11', hebrew: 'יום', hebrewWithVowels: 'יוֹם', french: 'Jour' },
      { id: '12', hebrew: 'לילה', hebrewWithVowels: 'לַיְלָה', french: 'Nuit' },
      { id: '13', hebrew: 'שעה', hebrewWithVowels: 'שָׁעָה', french: 'Heure' },
      { id: '14', hebrew: 'דקה', hebrewWithVowels: 'דַּקָּה', french: 'Minute' },
      { id: '15', hebrew: 'שנייה', hebrewWithVowels: 'שְׁנִיָּה', french: 'Seconde' },
      { id: '16', hebrew: 'בוקר', hebrewWithVowels: 'בוֹקֶר', french: 'Matin' },
      { id: '17', hebrew: 'צהריים', hebrewWithVowels: 'צָהֳרַיִם', french: 'Midi/Après-midi' },
      { id: '18', hebrew: 'ערב', hebrewWithVowels: 'עֶרֶב', french: 'Soir' },
      { id: '19', hebrew: 'חורף', hebrewWithVowels: 'חוֹרֶף', french: 'Hiver' },
      { id: '20', hebrew: 'אביב', hebrewWithVowels: 'אָבִיב', french: 'Printemps' },
      { id: '21', hebrew: 'קיץ', hebrewWithVowels: 'קַיִץ', french: 'Été' },
      { id: '22', hebrew: 'סתיו', hebrewWithVowels: 'סְתָיו', french: 'Automne' },
      { id: '23', hebrew: 'יום כיום', hebrewWithVowels: 'יוֹם כְּיוֹם', french: 'Aujourd\'hui' },
      { id: '24', hebrew: 'מחר', hebrewWithVowels: 'מָחָר', french: 'Demain' },
      { id: '25', hebrew: 'אתמול', hebrewWithVowels: 'אֶתְמוֹל', french: 'Hier' },
    ],
  },
  {
    id: 'nature',
    name: 'Nature & Environnement',
    description: 'Vocabulaire naturel et écologique',
    words: [
      { id: '1', hebrew: 'עץ', hebrewWithVowels: 'עֵץ', french: 'Arbre' },
      { id: '2', hebrew: 'פרח', hebrewWithVowels: 'פֶּרַח', french: 'Fleur' },
      { id: '3', hebrew: 'דשא', hebrewWithVowels: 'דֶּשֶׁא', french: 'Herbe' },
      { id: '4', hebrew: 'מים', hebrewWithVowels: 'מַיִם', french: 'Eau' },
      { id: '5', hebrew: 'שמש', hebrewWithVowels: 'שֶׁמֶשׁ', french: 'Soleil' },
      { id: '6', hebrew: 'ירח', hebrewWithVowels: 'יָרֵחַ', french: 'Lune' },
      { id: '7', hebrew: 'כוכב', hebrewWithVowels: 'כּוֹכָב', french: 'Étoile' },
      { id: '8', hebrew: 'ענן', hebrewWithVowels: 'עָנָן', french: 'Nuage' },
      { id: '9', hebrew: 'גשם', hebrewWithVowels: 'גֶּשֶׁם', french: 'Pluie' },
      { id: '10', hebrew: 'קשת', hebrewWithVowels: 'קֶשֶׁת', french: 'Arc-en-ciel' },
      { id: '11', hebrew: 'טל', hebrewWithVowels: 'טַל', french: 'Rosée' },
      { id: '12', hebrew: 'קרח', hebrewWithVowels: 'קַרַח', french: 'Glace' },
      { id: '13', hebrew: 'שלג', hebrewWithVowels: 'שֶׁלֶג', french: 'Neige' },
      { id: '14', hebrew: 'רוח', hebrewWithVowels: 'רוּחַ', french: 'Vent' },
      { id: '15', hebrew: 'סערה', hebrewWithVowels: 'סְעָרָה', french: 'Tempête' },
      { id: '16', hebrew: 'יער', hebrewWithVowels: 'יַעַר', french: 'Forêt' },
      { id: '17', hebrew: 'גן', hebrewWithVowels: 'גַּן', french: 'Jardin' },
      { id: '18', hebrew: 'חול', hebrewWithVowels: 'חוֹל', french: 'Sable' },
      { id: '19', hebrew: 'אבן', hebrewWithVowels: 'אֶבֶן', french: 'Pierre/Roche' },
      { id: '20', hebrew: 'דרך', hebrewWithVowels: 'דֶּרֶךְ', french: 'Route/Chemin' },
      { id: '21', hebrew: 'גבעה', hebrewWithVowels: 'גִּבְעָה', french: 'Colline' },
      { id: '22', hebrew: 'הר', hebrewWithVowels: 'הַר', french: 'Montagne' },
      { id: '23', hebrew: 'בקעה', hebrewWithVowels: 'בִּקְעָה', french: 'Vallée' },
      { id: '24', hebrew: 'חוף', hebrewWithVowels: 'חוֹף', french: 'Plage/Côte' },
      { id: '25', hebrew: 'טבע', hebrewWithVowels: 'טֶבַע', french: 'Nature' },
    ],
  },
  {
    id: 'travel',
    name: 'Voyage & Transport',
    description: 'Vocabulaire de voyage',
    words: [
      { id: '1', hebrew: 'רכבת', hebrewWithVowels: 'רַכֶּבֶת', french: 'Train' },
      { id: '2', hebrew: 'מכונית', hebrewWithVowels: 'מְכוֹנִית', french: 'Voiture' },
      { id: '3', hebrew: 'אוטובוס', hebrewWithVowels: 'אוֹטוֹבּוּס', french: 'Bus' },
      { id: '4', hebrew: 'תעופה', hebrewWithVowels: 'תְּעוּפָה', french: 'Aviation' },
      { id: '5', hebrew: 'דרכון', hebrewWithVowels: 'דַּרְכּוֹן', french: 'Passeport' },
      { id: '6', hebrew: 'כרטיס', hebrewWithVowels: 'כַּרְטִיס', french: 'Billet' },
      { id: '7', hebrew: 'מלון', hebrewWithVowels: 'מָלוֹן', french: 'Hôtel' },
      { id: '8', hebrew: 'תיירות', hebrewWithVowels: 'תַּיָּרוּת', french: 'Tourisme' },
      { id: '9', hebrew: 'מזוודה', hebrewWithVowels: 'מִזְוָדָה', french: 'Valise' },
      { id: '10', hebrew: 'מפה', hebrewWithVowels: 'מַפָּה', french: 'Carte' },
      { id: '11', hebrew: 'טיסה', hebrewWithVowels: 'טִיסָה', french: 'Vol' },
      { id: '12', hebrew: 'שדה תעופה', hebrewWithVowels: 'שְׂדֵה תְּעוּפָה', french: 'Aéroport' },
      { id: '13', hebrew: 'תחנה', hebrewWithVowels: 'תַּחֲנָה', french: 'Gare/Station' },
      { id: '14', hebrew: 'כביש', hebrewWithVowels: 'כְּבִישׁ', french: 'Route/Autoroute' },
      { id: '15', hebrew: 'סיור', hebrewWithVowels: 'סִיּוּר', french: 'Excursion/Visite' },
      { id: '16', hebrew: 'יעד', hebrewWithVowels: 'יַעַד', french: 'Destination' },
      { id: '17', hebrew: 'טיול', hebrewWithVowels: 'טִיּוּל', french: 'Voyage/Excursion' },
      { id: '18', hebrew: 'מסעות', hebrewWithVowels: 'מַסְעוֹת', french: 'Voyages' },
      { id: '19', hebrew: 'אוויר', hebrewWithVowels: 'אָוִיר', french: 'Air/Atmosphère' },
      { id: '20', hebrew: 'זיכרונות', hebrewWithVowels: 'זִיכְרוֹנוֹת', french: 'Souvenirs' },
      { id: '21', hebrew: 'עלות', hebrewWithVowels: 'עֲלוּת', french: 'Coût' },
      { id: '22', hebrew: 'מטייל', hebrewWithVowels: 'מִטַּיֵּל', french: 'Touriste' },
      { id: '23', hebrew: 'מהנה', hebrewWithVowels: 'מְהַנֶּה', french: 'Amusant' },
      { id: '24', hebrew: 'קומפס', hebrewWithVowels: 'קוֹמְפַּס', french: 'Boussole' },
      { id: '25', hebrew: 'מסע ביחד', hebrewWithVowels: 'מַסַּע בְּיַחַד', french: 'Compagnon de voyage' },
    ],
  },
  {
    id: 'learning',
    name: 'Apprentissage & Étude',
    description: 'Vocabulaire scolaire et éducatif',
    words: [
      { id: '1', hebrew: 'ספר', hebrewWithVowels: 'סֵפֶר', french: 'Livre' },
      { id: '2', hebrew: 'מחברת', hebrewWithVowels: 'מַחְבֶּרֶת', french: 'Cahier' },
      { id: '3', hebrew: 'עט', hebrewWithVowels: 'עֵט', french: 'Stylo' },
      { id: '4', hebrew: 'שעיל', hebrewWithVowels: 'שְׁעִיל', french: 'Exercice' },
      { id: '5', hebrew: 'שיעור', hebrewWithVowels: 'שִׁיעוּר', french: 'Leçon/Cours' },
      { id: '6', hebrew: 'מבחן', hebrewWithVowels: 'מִבְחָן', french: 'Examen' },
      { id: '7', hebrew: 'דברי ספר', hebrewWithVowels: 'דִּבְרֵי סֵפֶר', french: 'Littérature' },
      { id: '8', hebrew: 'תלמיד', hebrewWithVowels: 'תַּלְמִיד', french: 'Étudiant' },
      { id: '9', hebrew: 'מורה', hebrewWithVowels: 'מוֹרָה', french: 'Professeur' },
      { id: '10', hebrew: 'ידע', hebrewWithVowels: 'יְדַע', french: 'Connaissance' },
      { id: '11', hebrew: 'בית ספר', hebrewWithVowels: 'בֵּית סֵפֶר', french: 'École' },
      { id: '12', hebrew: 'כיתה', hebrewWithVowels: 'כִּיתָה', french: 'Classe' },
      { id: '13', hebrew: 'לוח', hebrewWithVowels: 'לוּחַ', french: 'Tableau' },
      { id: '14', hebrew: 'עיפרון', hebrewWithVowels: 'עִפָּרוֹן', french: 'Crayon' },
      { id: '15', hebrew: 'מחק', hebrewWithVowels: 'מַחַק', french: 'Gomme' },
      { id: '16', hebrew: 'סרגל', hebrewWithVowels: 'סַרְגֵּל', french: 'Règle' },
      { id: '17', hebrew: 'מסור', hebrewWithVowels: 'מַסּוֹר', french: 'Enseignement' },
      { id: '18', hebrew: 'קריאה', hebrewWithVowels: 'קְרִיאָה', french: 'Lecture' },
      { id: '19', hebrew: 'כתיבה', hebrewWithVowels: 'כְּתִיבָה', french: 'Écriture' },
      { id: '20', hebrew: 'חשבון', hebrewWithVowels: 'חֶשְׁבּוֹן', french: 'Mathématiques' },
      { id: '21', hebrew: 'היסטוריה', hebrewWithVowels: 'הִיסְטוֹרְיָה', french: 'Histoire' },
      { id: '22', hebrew: 'גיאוגרפיה', hebrewWithVowels: 'גְּיוֹגְרָפְיָה', french: 'Géographie' },
      { id: '23', hebrew: 'מדע', hebrewWithVowels: 'מַדַּע', french: 'Science' },
      { id: '24', hebrew: 'ציון', hebrewWithVowels: 'צִיּוֹן', french: 'Note/Marque' },
      { id: '25', hebrew: 'תעודה', hebrewWithVowels: 'תְּעוּדָה', french: 'Diplôme/Certificat' },
    ],
  },
];
