export interface Word {
  id: string;
  hebrew: string;
  hebrewWithVowels?: string;
  french: string;
}

export interface VocabularyList {
  id: string;
  name: string;
  description: string;
  words: Word[];
}

export const vocabularyLists: VocabularyList[] = [
  {
    id: 'maison',
    name: 'Maison & Habitat',
    description: 'Vocabulaire de la maison et aménagement intérieur',
    words: [
      { id: '1', hebrew: 'דלת', hebrewWithVowels: 'דַלֶת', french: 'Porte' },
      { id: '2', hebrew: 'חלון', hebrewWithVowels: 'חַלוֹן', french: 'Fenêtre' },
      { id: '3', hebrew: 'מדרגות', hebrewWithVowels: 'מַדְרֵגוֹת', french: 'Escaliers' },
      { id: '4', hebrew: 'קיר', hebrewWithVowels: 'קִיר', french: 'Mur' },
      { id: '5', hebrew: 'תקרה', hebrewWithVowels: 'תִקְרָה', french: 'Plafond' },
      { id: '6', hebrew: 'רצפה', hebrewWithVowels: 'רִצְפָה', french: 'Sol/Plancher' },
      { id: '7', hebrew: 'ריהוט', hebrewWithVowels: 'רִיהוּט', french: 'Mobilier' },
      { id: '8', hebrew: 'מטבח', hebrewWithVowels: 'מִטְבַּח', french: 'Cuisine' },
      { id: '9', hebrew: 'חדר שינה', hebrewWithVowels: 'חֶדֶר שֵׁינָה', french: 'Chambre à coucher' },
      { id: '10', hebrew: 'אמבטיה', hebrewWithVowels: 'אַמְבַּטְיָה', french: 'Salle de bain' },
      { id: '11', hebrew: 'סלון', hebrewWithVowels: 'סָלוֹן', french: 'Salon' },
      { id: '12', hebrew: 'משכנתא', hebrewWithVowels: 'מִשְׁכַּנְתָּא', french: 'Hypothèque' },
      { id: '13', hebrew: 'דירה', hebrewWithVowels: 'דִּירָה', french: 'Appartement' },
      { id: '14', hebrew: 'בית', hebrewWithVowels: 'בַּיִת', french: 'Maison' },
      { id: '15', hebrew: 'חדר', hebrewWithVowels: 'חֶדֶר', french: 'Chambre' },
      { id: '16', hebrew: 'מקרר', hebrewWithVowels: 'מִקְרֵר', french: 'Réfrigérateur' },
      { id: '17', hebrew: 'כיריים', hebrewWithVowels: 'כִּיְרַיִם', french: 'Cuisinière' },
      { id: '18', hebrew: 'כיור', hebrewWithVowels: 'כִּיּוֹר', french: 'Évier' },
      { id: '19', hebrew: 'ספה', hebrewWithVowels: 'סָפָה', french: 'Canapé' },
      { id: '20', hebrew: 'שולחן', hebrewWithVowels: 'שֻׁלְחָן', french: 'Table' },
      { id: '21', hebrew: 'כסא', hebrewWithVowels: 'כִּסֵּא', french: 'Chaise' },
      { id: '22', hebrew: 'מיטה', hebrewWithVowels: 'מִיטָּה', french: 'Lit' },
      { id: '23', hebrew: 'ארון', hebrewWithVowels: 'אָרוֹן', french: 'Armoire' },
      { id: '24', hebrew: 'מראה', hebrewWithVowels: 'מִרְאָה', french: 'Miroir' },
      { id: '25', hebrew: 'נר', hebrewWithVowels: 'נֵר', french: 'Chandelle' },
    ],
  },
  {
    id: 'emotions',
    name: 'Émotions & Sentiments',
    description: 'Verbes et vocabulaire des émotions',
    words: [
      { id: '1', hebrew: 'להרגיש', french: 'Sentir/Ressentir' },
      { id: '2', hebrew: 'לשמוח', french: 'Se réjouir' },
      { id: '3', hebrew: 'להצטער', french: 'Regretter' },
      { id: '4', hebrew: 'להתרגז', french: 'S\'énerver/Se fâcher' },
      { id: '5', hebrew: 'לפחד', french: 'Avoir peur' },
      { id: '6', hebrew: 'להתקצף', french: 'Être furieux' },
      { id: '7', hebrew: 'להתעצבן', french: 'Être déprimé' },
      { id: '8', hebrew: 'להרגע', french: 'Se calmer' },
      { id: '9', hebrew: 'להיות עצוב', french: 'Être triste' },
      { id: '10', hebrew: 'לחוש אימה', french: 'Ressentir de la terreur' },
      { id: '11', hebrew: 'אהבה', french: 'Amour' },
      { id: '12', hebrew: 'שנאה', french: 'Haine' },
      { id: '13', hebrew: 'תקווה', french: 'Espoir' },
      { id: '14', hebrew: 'ייאוש', french: 'Désespoir' },
      { id: '15', hebrew: 'כמיהה', french: 'Nostalgie/Yearning' },
      { id: '16', hebrew: 'שמחה', french: 'Joie' },
      { id: '17', hebrew: 'עצב', french: 'Tristesse' },
      { id: '18', hebrew: 'כעס', french: 'Colère' },
      { id: '19', hebrew: 'בושה', french: 'Honte' },
      { id: '20', hebrew: 'גאווה', french: 'Fierté' },
      { id: '21', hebrew: 'קנאה', french: 'Jalousie' },
      { id: '22', hebrew: 'חסד', french: 'Compassion' },
      { id: '23', hebrew: 'צער', french: 'Chagrin' },
      { id: '24', hebrew: 'הנאה', french: 'Plaisir' },
      { id: '25', hebrew: 'דאגה', french: 'Inquiétude' },
    ],
  },
  {
    id: 'family',
    name: 'Famille & Relations',
    description: 'Vocabulaire familial avancé',
    words: [
      { id: '1', hebrew: 'סב/סבה', french: 'Grand-père/mère' },
      { id: '2', hebrew: 'דוד/דודה', french: 'Oncle/Tante' },
      { id: '3', hebrew: 'בן דוד/בת דודה', french: 'Cousin/Cousine' },
      { id: '4', hebrew: 'חמורה', french: 'Belle-mère (époux)' },
      { id: '5', hebrew: 'חתן', french: 'Gendre' },
      { id: '6', hebrew: 'כלה', french: 'Mariée' },
      { id: '7', hebrew: 'אחיינייה', french: 'Nièce' },
      { id: '8', hebrew: 'אחיין', french: 'Neveu' },
      { id: '9', hebrew: 'משפחה גדולה', french: 'Grande famille' },
      { id: '10', hebrew: 'יחסים משפחתיים', french: 'Relations familiales' },
      { id: '11', hebrew: 'אב', french: 'Père' },
      { id: '12', hebrew: 'אם', french: 'Mère' },
      { id: '13', hebrew: 'בן', french: 'Fils' },
      { id: '14', hebrew: 'בת', french: 'Fille' },
      { id: '15', hebrew: 'אח', french: 'Frère' },
      { id: '16', hebrew: 'אחות', french: 'Sœur' },
      { id: '17', hebrew: 'בעל', french: 'Mari/Époux' },
      { id: '18', hebrew: 'אישה', french: 'Femme/Épouse' },
      { id: '19', hebrew: 'ילד/ילדה', french: 'Enfant' },
      { id: '20', hebrew: 'חמי/חמות', french: 'Beau-père/mère' },
      { id: '21', hebrew: 'גיס', french: 'Beau-frère' },
      { id: '22', hebrew: 'גיסה', french: 'Belle-sœur' },
      { id: '23', hebrew: 'סמיך קרוב', french: 'Proche' },
      { id: '24', hebrew: 'מעמד משפחתי', french: 'Statut familial' },
      { id: '25', hebrew: 'תינוק', french: 'Bébé' },
    ],
  },
  {
    id: 'verbs',
    name: 'Verbes Courants',
    description: 'Verbes pratiques et fréquents',
    words: [
      { id: '1', hebrew: 'ללכת', french: 'Aller' },
      { id: '2', hebrew: 'לבוא', french: 'Venir' },
      { id: '3', hebrew: 'לשמוע', french: 'Entendre' },
      { id: '4', hebrew: 'לראות', french: 'Voir' },
      { id: '5', hebrew: 'לדבר', french: 'Parler' },
      { id: '6', hebrew: 'לשתוק', french: 'Se taire' },
      { id: '7', hebrew: 'לאכול', french: 'Manger' },
      { id: '8', hebrew: 'לשתות', french: 'Boire' },
      { id: '9', hebrew: 'לישון', french: 'Dormir' },
      { id: '10', hebrew: 'להיקום', french: 'Se lever' },
      { id: '11', hebrew: 'לכתוב', french: 'Écrire' },
      { id: '12', hebrew: 'לקרוא', french: 'Lire' },
      { id: '13', hebrew: 'להבין', french: 'Comprendre' },
      { id: '14', hebrew: 'ללמוד', french: 'Étudier' },
      { id: '15', hebrew: 'לעבוד', french: 'Travailler' },
      { id: '16', hebrew: 'לשחק', french: 'Jouer' },
      { id: '17', hebrew: 'לחיות', french: 'Vivre' },
      { id: '18', hebrew: 'למות', french: 'Mourir' },
      { id: '19', hebrew: 'לתת', french: 'Donner' },
      { id: '20', hebrew: 'לקחת', french: 'Prendre' },
      { id: '21', hebrew: 'לעזור', french: 'Aider' },
      { id: '22', hebrew: 'לחפש', french: 'Chercher' },
      { id: '23', hebrew: 'למצוא', french: 'Trouver' },
      { id: '24', hebrew: 'לחכות', french: 'Attendre' },
      { id: '25', hebrew: 'להכין', french: 'Préparer' },
    ],
  },
  {
    id: 'food',
    name: 'Nourriture & Cuisine',
    description: 'Aliments et vocabulaire culinaire',
    words: [
      { id: '1', hebrew: 'לחם', french: 'Pain' },
      { id: '2', hebrew: 'עוף', french: 'Volaille/Poulet' },
      { id: '3', hebrew: 'בשר', french: 'Viande' },
      { id: '4', hebrew: 'דגים', french: 'Poisson' },
      { id: '5', hebrew: 'ירקות', french: 'Légumes' },
      { id: '6', hebrew: 'פירות', french: 'Fruits' },
      { id: '7', hebrew: 'ביצה', french: 'Œuf' },
      { id: '8', hebrew: 'חומוס', french: 'Houmous' },
      { id: '9', hebrew: 'מלח', french: 'Sel' },
      { id: '10', hebrew: 'סוכר', french: 'Sucre' },
      { id: '11', hebrew: 'גבינה', french: 'Fromage' },
      { id: '12', hebrew: 'חלב', french: 'Lait' },
      { id: '13', hebrew: 'דבש', french: 'Miel' },
      { id: '14', hebrew: 'בטטה', french: 'Pomme de terre' },
      { id: '15', hebrew: 'עגבנייה', french: 'Tomate' },
      { id: '16', hebrew: 'מלפפון', french: 'Concombre' },
      { id: '17', hebrew: 'בצל', french: 'Oignon' },
      { id: '18', hebrew: 'שום', french: 'Ail' },
      { id: '19', hebrew: 'בננה', french: 'Banane' },
      { id: '20', hebrew: 'תפוח', french: 'Pomme' },
      { id: '21', hebrew: 'לימון', french: 'Citron' },
      { id: '22', hebrew: 'פסטה', french: 'Pâtes' },
      { id: '23', hebrew: 'אורז', french: 'Riz' },
      { id: '24', hebrew: 'טעם', french: 'Goût' },
      { id: '25', hebrew: 'מסעדה', french: 'Restaurant' },
    ],
  },
  {
    id: 'body',
    name: 'Corps & Santé',
    description: 'Parties du corps et vocabulaire médical',
    words: [
      { id: '1', hebrew: 'ראש', french: 'Tête' },
      { id: '2', hebrew: 'עיניים', french: 'Yeux' },
      { id: '3', hebrew: 'אוזן', french: 'Oreille' },
      { id: '4', hebrew: 'אף', french: 'Nez' },
      { id: '5', hebrew: 'פה', french: 'Bouche' },
      { id: '6', hebrew: 'שיניים', french: 'Dents' },
      { id: '7', hebrew: 'לב', french: 'Cœur' },
      { id: '8', hebrew: 'ריאות', french: 'Poumons' },
      { id: '9', hebrew: 'כאב', french: 'Douleur' },
      { id: '10', hebrew: 'חום', french: 'Fièvre' },
      { id: '11', hebrew: 'זרוע', french: 'Bras' },
      { id: '12', hebrew: 'רגל', french: 'Jambe' },
      { id: '13', hebrew: 'יד', french: 'Main' },
      { id: '14', hebrew: 'כף יד', french: 'Paume' },
      { id: '15', hebrew: 'אצבע', french: 'Doigt' },
      { id: '16', hebrew: 'כתף', french: 'Épaule' },
      { id: '17', hebrew: 'גב', french: 'Dos' },
      { id: '18', hebrew: 'בטן', french: 'Ventre' },
      { id: '19', hebrew: 'קרסול', french: 'Cheville' },
      { id: '20', hebrew: 'עצם', french: 'Os' },
      { id: '21', hebrew: 'שריר', french: 'Muscle' },
      { id: '22', hebrew: 'עור', french: 'Peau' },
      { id: '23', hebrew: 'דם', french: 'Sang' },
      { id: '24', hebrew: 'חולי', french: 'Maladie' },
      { id: '25', hebrew: 'רופא', french: 'Médecin' },
    ],
  },
  {
    id: 'work',
    name: 'Travail & Profession',
    description: 'Vocabulaire professionnel',
    words: [
      { id: '1', hebrew: 'עבודה', french: 'Travail' },
      { id: '2', hebrew: 'משרד', french: 'Bureau' },
      { id: '3', hebrew: 'מחשב', french: 'Ordinateur' },
      { id: '4', hebrew: 'טלפון', french: 'Téléphone' },
      { id: '5', hebrew: 'דוח', french: 'Rapport' },
      { id: '6', hebrew: 'פגישה', french: 'Réunion' },
      { id: '7', hebrew: 'שכר', french: 'Salaire' },
      { id: '8', hebrew: 'חוזה', french: 'Contrat' },
      { id: '9', hebrew: 'קריירה', french: 'Carrière' },
      { id: '10', hebrew: 'מעסיק', french: 'Employeur' },
      { id: '11', hebrew: 'עובד', french: 'Employé' },
      { id: '12', hebrew: 'מנהל', french: 'Directeur/Manager' },
      { id: '13', hebrew: 'פרויקט', french: 'Projet' },
      { id: '14', hebrew: 'תיקייה', french: 'Dossier/Portefeuille' },
      { id: '15', hebrew: 'דדלין', french: 'Délai' },
      { id: '16', hebrew: 'ישיבה', french: 'Séance/Réunion' },
      { id: '17', hebrew: 'עומק', french: 'Profondeur' },
      { id: '18', hebrew: 'הצלחה', french: 'Succès' },
      { id: '19', hebrew: 'כישרון', french: 'Talent' },
      { id: '20', hebrew: 'ניסיון', french: 'Expérience' },
      { id: '21', hebrew: 'חינוך', french: 'Éducation/Formation' },
      { id: '22', hebrew: 'מקצוע', french: 'Profession' },
      { id: '23', hebrew: 'אחראיות', french: 'Responsabilité' },
      { id: '24', hebrew: 'שיתוף פעולה', french: 'Collaboration' },
      { id: '25', hebrew: 'קידום', french: 'Promotion' },
    ],
  },
  {
    id: 'time',
    name: 'Temps & Calendrier',
    description: 'Jours, mois, saisons',
    words: [
      { id: '1', hebrew: 'יום ראשון', french: 'Dimanche' },
      { id: '2', hebrew: 'יום שני', french: 'Lundi' },
      { id: '3', hebrew: 'יום שלישי', french: 'Mardi' },
      { id: '4', hebrew: 'יום רביעי', french: 'Mercredi' },
      { id: '5', hebrew: 'יום חמישי', french: 'Jeudi' },
      { id: '6', hebrew: 'יום שישי', french: 'Vendredi' },
      { id: '7', hebrew: 'יום שבת', french: 'Samedi' },
      { id: '8', hebrew: 'חודש', french: 'Mois' },
      { id: '9', hebrew: 'עונה', french: 'Saison' },
      { id: '10', hebrew: 'שנה', french: 'Année' },
      { id: '11', hebrew: 'יום', french: 'Jour' },
      { id: '12', hebrew: 'לילה', french: 'Nuit' },
      { id: '13', hebrew: 'שעה', french: 'Heure' },
      { id: '14', hebrew: 'דקה', french: 'Minute' },
      { id: '15', hebrew: 'שנייה', french: 'Seconde' },
      { id: '16', hebrew: 'בוקר', french: 'Matin' },
      { id: '17', hebrew: 'צהריים', french: 'Midi/Après-midi' },
      { id: '18', hebrew: 'ערב', french: 'Soir' },
      { id: '19', hebrew: 'חורף', french: 'Hiver' },
      { id: '20', hebrew: 'אביב', french: 'Printemps' },
      { id: '21', hebrew: 'קיץ', french: 'Été' },
      { id: '22', hebrew: 'סתיו', french: 'Automne' },
      { id: '23', hebrew: 'יום כיום', french: 'Aujourd\'hui' },
      { id: '24', hebrew: 'מחר', french: 'Demain' },
      { id: '25', hebrew: 'אתמול', french: 'Hier' },
    ],
  },
  {
    id: 'nature',
    name: 'Nature & Environnement',
    description: 'Vocabulaire naturel et écologique',
    words: [
      { id: '1', hebrew: 'עץ', french: 'Arbre' },
      { id: '2', hebrew: 'פרח', french: 'Fleur' },
      { id: '3', hebrew: 'דשא', french: 'Herbe' },
      { id: '4', hebrew: 'מים', french: 'Eau' },
      { id: '5', hebrew: 'שמש', french: 'Soleil' },
      { id: '6', hebrew: 'ירח', french: 'Lune' },
      { id: '7', hebrew: 'כוכב', french: 'Étoile' },
      { id: '8', hebrew: 'ענן', french: 'Nuage' },
      { id: '9', hebrew: 'גשם', french: 'Pluie' },
      { id: '10', hebrew: 'קשת', french: 'Arc-en-ciel' },
      { id: '11', hebrew: 'טל', french: 'Rosée' },
      { id: '12', hebrew: 'קרח', french: 'Glace' },
      { id: '13', hebrew: 'שלג', french: 'Neige' },
      { id: '14', hebrew: 'רוח', french: 'Vent' },
      { id: '15', hebrew: 'סערה', french: 'Tempête' },
      { id: '16', hebrew: 'יער', french: 'Forêt' },
      { id: '17', hebrew: 'גן', french: 'Jardin' },
      { id: '18', hebrew: 'חול', french: 'Sable' },
      { id: '19', hebrew: 'אבן', french: 'Pierre/Roche' },
      { id: '20', hebrew: 'דרך', french: 'Route/Chemin' },
      { id: '21', hebrew: 'גבעה', french: 'Colline' },
      { id: '22', hebrew: 'הר', french: 'Montagne' },
      { id: '23', hebrew: 'בקעה', french: 'Vallée' },
      { id: '24', hebrew: 'חוף', french: 'Plage/Côte' },
      { id: '25', hebrew: 'טבע', french: 'Nature' },
    ],
  },
  {
    id: 'travel',
    name: 'Voyage & Transport',
    description: 'Vocabulaire de voyage',
    words: [
      { id: '1', hebrew: 'רכבת', french: 'Train' },
      { id: '2', hebrew: 'מכונית', french: 'Voiture' },
      { id: '3', hebrew: 'אוטובוס', french: 'Bus' },
      { id: '4', hebrew: 'תעופה', french: 'Aviation' },
      { id: '5', hebrew: 'דרכון', french: 'Passeport' },
      { id: '6', hebrew: 'כרטיס', french: 'Billet' },
      { id: '7', hebrew: 'מלון', french: 'Hôtel' },
      { id: '8', hebrew: 'תיירות', french: 'Tourisme' },
      { id: '9', hebrew: 'מזוודה', french: 'Valise' },
      { id: '10', hebrew: 'מפה', french: 'Carte' },
      { id: '11', hebrew: 'טיסה', french: 'Vol' },
      { id: '12', hebrew: 'שדה תעופה', french: 'Aéroport' },
      { id: '13', hebrew: 'תחנה', french: 'Gare/Station' },
      { id: '14', hebrew: 'כביש', french: 'Route/Autoroute' },
      { id: '15', hebrew: 'סיור', french: 'Excursion/Visite' },
      { id: '16', hebrew: 'יעד', french: 'Destination' },
      { id: '17', hebrew: 'טיול', french: 'Voyage/Excursion' },
      { id: '18', hebrew: 'מסעות', french: 'Voyages' },
      { id: '19', hebrew: 'אוויר', french: 'Air/Atmosphère' },
      { id: '20', hebrew: 'זיכרונות', french: 'Souvenirs' },
      { id: '21', hebrew: 'עלות', french: 'Coût' },
      { id: '22', hebrew: 'מטייל', french: 'Touriste' },
      { id: '23', hebrew: 'מהנה', french: 'Amusant' },
      { id: '24', hebrew: 'קומפס', french: 'Boussole' },
      { id: '25', hebrew: 'מסע ביחד', french: 'Compagnon de voyage' },
    ],
  },
  {
    id: 'learning',
    name: 'Apprentissage & Étude',
    description: 'Vocabulaire scolaire et éducatif',
    words: [
      { id: '1', hebrew: 'ספר', french: 'Livre' },
      { id: '2', hebrew: 'מחברת', french: 'Cahier' },
      { id: '3', hebrew: 'עט', french: 'Stylo' },
      { id: '4', hebrew: 'שעיל', french: 'Exercice' },
      { id: '5', hebrew: 'שיעור', french: 'Leçon/Cours' },
      { id: '6', hebrew: 'מבחן', french: 'Examen' },
      { id: '7', hebrew: 'דברי ספר', french: 'Littérature' },
      { id: '8', hebrew: 'תלמיד', french: 'Étudiant' },
      { id: '9', hebrew: 'מורה', french: 'Professeur' },
      { id: '10', hebrew: 'ידע', french: 'Connaissance' },
      { id: '11', hebrew: 'בית ספר', french: 'École' },
      { id: '12', hebrew: 'כיתה', french: 'Classe' },
      { id: '13', hebrew: 'לוח', french: 'Tableau' },
      { id: '14', hebrew: 'עיפרון', french: 'Crayon' },
      { id: '15', hebrew: 'מחק', french: 'Gomme' },
      { id: '16', hebrew: 'סרגל', french: 'Règle' },
      { id: '17', hebrew: 'מסור', french: 'Enseignement' },
      { id: '18', hebrew: 'קריאה', french: 'Lecture' },
      { id: '19', hebrew: 'כתיבה', french: 'Écriture' },
      { id: '20', hebrew: 'חשבון', french: 'Mathématiques' },
      { id: '21', hebrew: 'היסטוריה', french: 'Histoire' },
      { id: '22', hebrew: 'גיאוגרפיה', french: 'Géographie' },
      { id: '23', hebrew: 'מדע', french: 'Science' },
      { id: '24', hebrew: 'ציון', french: 'Note/Marque' },
      { id: '25', hebrew: 'תעודה', french: 'Diplôme/Certificat' },
    ],
  },
];
